# Specify the Kubernetes API version for Service resources
apiVersion: v1

# Define the type of Kubernetes resource (Service exposes pods to network traffic)
kind: Service

# Metadata section: information about this Service
metadata:
  name: kubernetes-demo-api-service  # Name of the service
  labels:
    app: kubernetes-demo-api         # Label to identify this service

# Specification section: defines how the service works
spec:
  # Selector: determines which pods will receive traffic from this service
  # The service will route traffic to pods with matching labels
  selector:
    app: kubernetes-demo-api         # Route to pods with this label
  
  # Port configuration
  ports:
    - protocol: TCP                  # Use TCP protocol
      port: 3000                     # Port exposed by the service (internal cluster port)
      targetPort: 3000               # Port on the container where traffic is sent
  
  # Service type determines how the service is exposed
  # NodePort: Exposes the service on each node's IP at a static port (30000-32767)
  # For production cloud environments, change to LoadBalancer
  type: NodePort
